### ISSUE TITLE
ERROR in initial install/setup

### ISSUE THREAD

**Issue by iworks** [iworks/iworks-pwa#5]
hello. my search for a “simple” PWA plugin lead me to yours. so i went ahead & installed it in a staging environment that my server/host provides (SiteGround). so my problems might be due to that (not sure). the staged site is password protected too.

upon activation i made my way to the Settings > PWA page, and at the top it says:

```
ERROR: PWA – simple way to Progressive Web App

The “manifest.json” file is no reachable.
Please change your permalinks settings or server rewrite rules.
```

clicking on the “manifest.json” link opens that file. i can see the json code, so i’m not sure why it says it’s not reachable.

so then i clicked on the “change your permalinks” link and i “flushed” them. note: my permalink structure is using the “Custom Structure” option with “/%category%/%postname%/” in that form field. would that be causing the problem? i don’t really want to change that if i don’t have to.

now, if i make a minor change (like to the short name) and click the “Save Changes” button, that error message goes away & i get the “Settings saved” confirmation.

BUT, if i go away then come back or reload the page, then that same error message re-appears. AND not only on the PWA settings page, but on ALL admin pages.

so what am i missing? is it just because it’s on a staged & password protected site? any ideas?

thanks.

original: https://wordpress.org/support/topic/error-in-initial-install-setup/

**Comment by vitalii-work** [comment]
The message "The “manifest.json” file is no reachable.
Please change your permalinks settings or server rewrite rules." also appears to me sometimes.

My site isn't protected with basic HTTP authentication or any other type of password protection.

A quick workaround that helps me looks something like this:
1. Change permalinks to a different format  and save (2 times).
2. Deactivate this PWA plugin and another plugin that uses a serviceworker.
3. Change permalinks back to the desired format and save.
4. Activate the plugins.

**Comment by iworks** [comment]
I added inline explanation why those requests are missing - you have to update serwer rewrite rules.

I do not plan save those files. I'm sorry - it generally work well.

https://github.com/iworks/iworks-pwa/releases/tag/1.6.5
