### ISSUE TITLE
manifest.json has an issue with icons array, "purpose": "any maskable" is not acceptable

### ISSUE THREAD

**Issue by vitalii-work** [iworks/iworks-pwa#6]
When I tried to package our PWA for publishing in Google Play using [PWABuilder](https://docs.pwabuilder.com/#/builder/quick-start), I got an error related to the icons array in manifest.json. 

> If your icons array includes a maskable icon, this must be included as a separate icon, and can’t be added as a dual icon type (like `any maskable`, for example). This is because using maskable icons as any can result in icons not being displayed optimally.
Source:
https://docs.pwabuilder.com/#/builder/manifest?id=icons

When I manually created manifest.json file (copied and pasted the content of the original manifest.json file generated by your PWA plugin) and updated the icons array, the issue disappeared and I was able to package our PWA.

### Also, I have a question:
Why doesn't the plugin create the manifest.json file in the WP site root directory?
It would be useful to have it there to make edits when necessary.

**Comment by iworks** [comment]
@vitalii-work 
> Why doesn't the plugin create the manifest.json file in the WP site root directory?
There is no file. It is dynamically generated (with cache).

**Comment by vitalii-work** [comment]
@iworks, what if changing the logic of the plugin to generate a real manifest.json file will be a solution to another issue #5 (The “manifest.json” file is no reachable.")?

**Comment by iworks** [comment]
Thank you! It should be fixed here: https://github.com/iworks/iworks-pwa/releases/tag/1.6.5
